import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const ok=()=>new Response("ok",{status:200});
const env=(k)=>Deno.env.get(k)??"";
let BOT_TOKEN="";
const TG=()=>`https://api.telegram.org/bot${BOT_TOKEN}`;
async function tg(m,b){return fetch(`${TG()}/${m}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});}
async function send(chatId,text,opts){opts=opts||{};const chunks=text.match(/[\s\S]{1,3800}/g)||[text];for(let i=0;i<chunks.length;i++){const body={chat_id:chatId,text:chunks[i]};if(opts.html)body.parse_mode="HTML";if(i===chunks.length-1&&opts.markup)body.reply_markup=opts.markup;await tg("sendMessage",body);}}
const FAKE_DOMAIN="@sanatsabz.local";
const fmt=(n)=>(Number(n)||0).toLocaleString("en-US");
const isoOf=(d)=>d.toISOString().slice(0,10);
function esc(s){return String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function toJalali(gy,gm,gd){const g=[0,31,59,90,120,151,181,212,243,273,304,334];let jy=gy<=1600?0:979;gy-=gy<=1600?621:1600;const gy2=gm>2?gy+1:gy;let days=365*gy+Math.floor((gy2+3)/4)-Math.floor((gy2+99)/100)+Math.floor((gy2+399)/400)-80+gd+g[gm-1];jy+=33*Math.floor(days/12053);days%=12053;jy+=4*Math.floor(days/1461);days%=1461;if(days>365){jy+=Math.floor((days-1)/365);days=(days-1)%365;}const jm=days<186?1+Math.floor(days/31):7+Math.floor((days-186)/30);const jd=1+(days<186?days%31:(days-186)%30);return jy+"/"+String(jm).padStart(2,"0")+"/"+String(jd).padStart(2,"0");}
function jFull(iso){const p=String(iso).slice(0,10).split("-").map(Number);return p.length<3?iso:toJalali(p[0],p[1],p[2]);}
function jShort(iso){return jFull(iso).slice(5);}
function jMonth(iso){return jFull(iso).slice(0,7);}

const KB={keyboard:[[{text:"🏭 تولید"},{text:"💰 فروش"}],[{text:"🧱 انبار"},{text:"🏦 خزانه"}],[{text:"🧑‍💼 منابع انسانی"},{text:"📈 مالی"}],[{text:"🧾 چک‌ها"},{text:"📊 نمودارها"}],[{text:"❓ راهنما"},{text:"🚪 خروج"}]],resize_keyboard:true,is_persistent:true};
const RM={remove_keyboard:true};
const CHARTS_MENU={inline_keyboard:[[{text:"🏭 تولید روزانه",callback_data:"cht:prod_daily:month"},{text:"🏭 تولید خطوط",callback_data:"cht:prod_line"}],[{text:"🗑 ضایعات",callback_data:"cht:waste_daily:month"},{text:"⛔ توقف (نوع)",callback_data:"cht:stops_type:month"}],[{text:"💰 فروش ماهانه",callback_data:"cht:sales_monthly"},{text:"⏳ سن بدهی",callback_data:"cht:aging"}],[{text:"🏦 موجودی نقد",callback_data:"cht:cash"},{text:"🧱 ارزش مواد",callback_data:"cht:raw_value"}],[{text:"🧑‍💼 پرسنل واحدها",callback_data:"cht:hr_dept"}]]};
const BTN={"🏭 تولید":"production","💰 فروش":"sales","🧱 انبار":"inventory","🏦 خزانه":"treasury","🧑‍💼 منابع انسانی":"hr","📈 مالی":"finance","🧾 چک‌ها":"checks"};
const CMD={"/tolid":"production","/forush":"sales","/anbar":"inventory","/khazane":"treasury","/manabe":"hr","/mali":"finance","/chek":"checks"};
const HELP="🌿 من <b>سبزینه</b> هستم. از دکمه‌های پایین (گزارش، چک، 📊 نمودارها) استفاده کن یا هر سوالی را آزادانه بپرس.";

function normDate(v,isFrom){const s=String(v||"").trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const low=s.toLowerCase();const now=new Date();if(/دیروز|yesterday/.test(low))return isoOf(new Date(Date.now()-864e5));if(/امروز|today/.test(low))return isoOf(now);if(isFrom){if(/هفته|week/.test(low))return isoOf(new Date(Date.now()-7*864e5));if(/ماه|month/.test(low))return isoOf(new Date(now.getFullYear(),now.getMonth(),1));if(/سال|year/.test(low))return isoOf(new Date(now.getFullYear(),0,1));return isoOf(new Date(Date.now()-30*864e5));}return isoOf(now);}

const TOOLS=[{type:"function",function:{name:"report_production",description:"تولید",parameters:{type:"object",properties:{from:{type:"string"},to:{type:"string"}},required:["from","to"]}}},{type:"function",function:{name:"report_sales",description:"فروش",parameters:{type:"object",properties:{from:{type:"string"},to:{type:"string"}},required:["from","to"]}}},{type:"function",function:{name:"report_inventory",description:"موجودی",parameters:{type:"object",properties:{}}}},{type:"function",function:{name:"report_treasury",description:"خزانه",parameters:{type:"object",properties:{}}}},{type:"function",function:{name:"report_hr",description:"منابع انسانی",parameters:{type:"object",properties:{}}}},{type:"function",function:{name:"report_financial",description:"سود و زیان",parameters:{type:"object",properties:{from:{type:"string"},to:{type:"string"}},required:["from","to"]}}},{type:"function",function:{name:"sql_query",description:"SELECT فقط. daily_reports(date,production,waste,line,shift,operator), production_stops(stop_date,stop_type,duration_min,line,reason), invoices(invoice_date,total,paid,customer_name,status), customers(name), rawmats(name,stock,price,min_stock), treasury_accounts, treasury_checks(due_date,amount,status,direction), acc_voucher_lines(account_code,debit,credit), hr_employees(first_name,last_name,department,active), hr_attendance(att_date,status), hr_leaves(status,kind). تاریخ ISO.",parameters:{type:"object",properties:{query:{type:"string"}},required:["query"]}}}];
async function runTool(supa,name,args){const num=(v)=>Number(v)||0;
 if(name==="report_production"){const from=normDate(args.from,true),to=normDate(args.to,false);const q1=await supa.from("daily_reports").select("production,waste,line").gte("date",from).lte("date",to);const q2=await supa.from("production_stops").select("stop_type,duration_min").gte("stop_date",from).lte("stop_date",to);const dr=q1.data||[],st=q2.data||[];const prod=dr.reduce((s,r)=>s+num(r.production),0),waste=dr.reduce((s,r)=>s+num(r.waste),0);const byLine={};dr.forEach((r)=>{const l=r.line||"نامشخص";byLine[l]=(byLine[l]||0)+num(r.production);});const stops={};st.forEach((r)=>{stops[r.stop_type]=(stops[r.stop_type]||0)+num(r.duration_min);});return {total_production_kg:prod,total_waste_kg:waste,efficiency_pct:prod+waste>0?Math.round(prod/(prod+waste)*100):0,production_by_line:byLine,stop_minutes_by_type:stops};}
 if(name==="report_sales"){const from=normDate(args.from,true),to=normDate(args.to,false);const q=await supa.from("invoices").select("total,paid,customer_name").gte("invoice_date",from).lte("invoice_date",to);const data=q.data||[];const total=data.reduce((s,r)=>s+num(r.total),0),paid=data.reduce((s,r)=>s+num(r.paid),0);const byC={};data.forEach((r)=>{const c=r.customer_name||"—";byC[c]=(byC[c]||0)+num(r.total);});return {invoice_count:data.length,total_sales:total,total_received:paid,total_receivable:total-paid,top_customers:Object.entries(byC).sort((a,b)=>b[1]-a[1]).slice(0,5)};}
 if(name==="report_inventory"){const q=await supa.from("rawmats").select("name,stock,price,min_stock");const data=q.data||[];return {item_count:data.length,total_value:data.reduce((s,r)=>s+num(r.stock)*num(r.price),0),low_stock:data.filter((r)=>num(r.min_stock)>0&&num(r.stock)<=num(r.min_stock)).map((r)=>({name:r.name,stock:num(r.stock),min:num(r.min_stock)}))};}
 if(name==="report_treasury"){const qa=await supa.from("treasury_accounts").select("id,name,opening_balance");const qt=await supa.from("treasury_transactions").select("treasury_account_id,direction,amount");const bal={};(qa.data||[]).forEach((a)=>{bal[a.id]={name:a.name,balance:num(a.opening_balance)};});(qt.data||[]).forEach((t)=>{if(bal[t.treasury_account_id])bal[t.treasury_account_id].balance+=(t.direction==="receipt"?1:-1)*num(t.amount);});const qc=await supa.from("treasury_checks").select("direction,amount,status,due_date");const inflow=(qc.data||[]).filter((c)=>c.status==="in_hand"||c.status==="deposited");return {total_cash:Object.values(bal).reduce((s,a)=>s+a.balance,0),received_checks_pending:inflow.filter((c)=>c.direction==="received").reduce((s,c)=>s+num(c.amount),0),issued_checks_pending:inflow.filter((c)=>c.direction==="issued").reduce((s,c)=>s+num(c.amount),0),checks_next_7_days:inflow.filter((c)=>c.due_date&&c.due_date<=isoOf(new Date(Date.now()+7*864e5))).length};}
 if(name==="report_hr"){const qe=await supa.from("hr_employees").select("active");const today=isoOf(new Date());const qa=await supa.from("hr_attendance").select("status").eq("att_date",today);const ql=await supa.from("hr_leaves").select("status").eq("status","submitted");return {active_employees:(qe.data||[]).filter((e)=>e.active!==false).length,present_today:(qa.data||[]).filter((a)=>a.status==="present").length,pending_leaves:(ql.data||[]).length};}
 if(name==="report_financial"){const from=normDate(args.from,true),to=normDate(args.to,false);const qv=await supa.from("acc_vouchers").select("id").eq("status","posted").gte("voucher_date",from).lte("voucher_date",to);const ids=new Set((qv.data||[]).map((x)=>x.id));const ql=await supa.from("acc_voucher_lines").select("voucher_id,account_code,debit,credit");let inc=0,exp=0;(ql.data||[]).forEach((l)=>{if(!ids.has(l.voucher_id))return;const c=String(l.account_code||"");if(c.charAt(0)==="4")inc+=num(l.credit)-num(l.debit);if(c.charAt(0)==="5")exp+=num(l.debit)-num(l.credit);});return {total_income:inc,total_expense:exp,net_profit:inc-exp};}
 if(name==="sql_query"){const r=await supa.rpc("bot_readonly_sql",{p_sql:args.query});return r.error?{error:r.error.message}:{rows:r.data};}
 return {error:"unknown"};}

function rangeOf(range){const now=new Date();const today=isoOf(now);const yst=isoOf(new Date(Date.now()-864e5));if(range==="today")return {from:yst,to:yst,label:"دیروز"};if(range==="week")return {from:isoOf(new Date(Date.now()-6*864e5)),to:today,label:"۷ روز اخیر"};return {from:isoOf(new Date(now.getFullYear(),now.getMonth(),1)),to:today,label:"این ماه"};}
function inlineFor(kind,range){range=range||"month";const rows=[];if(kind==="production"||kind==="sales"||kind==="finance")rows.push([{text:(range==="today"?"✅ ":"")+"📅 دیروز",callback_data:"rng:"+kind+":today"},{text:(range==="week"?"✅ ":"")+"📅 هفته",callback_data:"rng:"+kind+":week"},{text:(range==="month"?"✅ ":"")+"📅 ماه",callback_data:"rng:"+kind+":month"}]);if(kind==="production")rows.push([{text:"📊 نمودار همین بازه",callback_data:"cht:prod_daily:"+range}]);if(kind==="sales")rows.push([{text:"📊 نمودار فروش",callback_data:"cht:sales_monthly"}]);return rows.length?{inline_keyboard:rows}:undefined;}

async function reportText(supa,kind,range){
 if(kind==="production"){const r=rangeOf(range);const d=await runTool(supa,"report_production",{from:r.from,to:r.to});let lines="";Object.keys(d.production_by_line).forEach((l)=>{lines+="\n   – "+esc(l)+": <b>"+fmt(d.production_by_line[l])+"</b> kg";});let stops="";Object.keys(d.stop_minutes_by_type).forEach((t)=>{const tn=t==="production"?"تولیدی":t==="technical"?"فنی":"سایر";stops+="\n   – "+tn+": <b>"+fmt(d.stop_minutes_by_type[t])+"</b> دقیقه";});return "🏭 <b>گزارش تولید — "+r.label+"</b>\n• تولید کل: <b>"+fmt(d.total_production_kg)+"</b> kg\n• ضایعات: <b>"+fmt(d.total_waste_kg)+"</b> kg\n• راندمان: <b>"+d.efficiency_pct+"%</b>"+(lines?"\n📍 خطوط:"+lines:"")+(stops?"\n⛔ توقف:"+stops:"");}
 if(kind==="sales"){const r=rangeOf(range);const d=await runTool(supa,"report_sales",{from:r.from,to:r.to});let tops="";(d.top_customers||[]).forEach((e)=>{tops+="\n   – "+esc(e[0])+": <b>"+fmt(e[1])+"</b>";});return "💰 <b>گزارش فروش — "+r.label+"</b>\n• جمع فروش: <b>"+fmt(d.total_sales)+"</b> ریال\n• دریافت‌شده: <b>"+fmt(d.total_received)+"</b>\n• مطالبات: <b>"+fmt(d.total_receivable)+"</b>\n• تعداد فاکتور: <b>"+d.invoice_count+"</b>"+(tops?"\n🏆 مشتریان برتر:"+tops:"");}
 if(kind==="finance"){const r=rangeOf(range);const d=await runTool(supa,"report_financial",{from:r.from,to:r.to});return "📈 <b>سود و زیان — "+r.label+"</b>\n• درآمد: <b>"+fmt(d.total_income)+"</b>\n• هزینه: <b>"+fmt(d.total_expense)+"</b>\n• "+(d.net_profit>=0?"سود":"زیان")+" خالص: <b>"+fmt(Math.abs(d.net_profit))+"</b> ریال";}
 if(kind==="inventory"){const d=await runTool(supa,"report_inventory",{});let low="";d.low_stock.forEach((x)=>{low+="\n   – "+esc(x.name)+": <b>"+fmt(x.stock)+"</b> (حداقل "+fmt(x.min)+")";});return "🧱 <b>وضعیت انبار</b>\n• ارزش موجودی: <b>"+fmt(d.total_value)+"</b> ریال\n• اقلام کم‌موجودی: <b>"+d.low_stock.length+"</b>"+(low?"\n⚠️ نیاز به تأمین:"+low:"");}
 if(kind==="treasury"){const d=await runTool(supa,"report_treasury",{});return "🏦 <b>خزانه</b>\n• موجودی نقد/بانک: <b>"+fmt(d.total_cash)+"</b> ریال\n• چک دریافتی در جریان: <b>"+fmt(d.received_checks_pending)+"</b>\n• چک پرداختی در جریان: <b>"+fmt(d.issued_checks_pending)+"</b>\n• سررسید ۷ روز آینده: <b>"+d.checks_next_7_days+"</b> فقره";}
 if(kind==="hr"){const d=await runTool(supa,"report_hr",{});return "🧑‍💼 <b>منابع انسانی</b>\n• پرسنل فعال: <b>"+d.active_employees+"</b>\n• حاضر امروز: <b>"+d.present_today+"</b>\n• مرخصی در انتظار: <b>"+d.pending_leaves+"</b>";}
 if(kind==="checks"){const q=await supa.from("treasury_checks").select("direction,amount,status,due_date,party_name");const data=q.data||[];const today=isoOf(new Date());const inflow=data.filter((c)=>c.status==="in_hand"||c.status==="deposited");const soon=inflow.filter((c)=>c.due_date&&c.due_date<=isoOf(new Date(Date.now()+7*864e5))).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)));const overdue=inflow.filter((c)=>c.due_date&&c.due_date<today);const bounced=data.filter((c)=>c.status==="bounced");let list="";soon.slice(0,10).forEach((c)=>{list+="\n   – "+(c.direction==="received"?"دریافتی":"پرداختی")+" "+fmt(c.amount)+" — "+jFull(c.due_date)+(c.party_name?" ("+esc(c.party_name)+")":"");});return "🧾 <b>چک‌ها</b>\n• سررسید تا ۷ روز آینده: <b>"+soon.length+"</b> فقره\n• معوق: <b>"+overdue.length+"</b>\n• برگشتی: <b>"+bounced.length+"</b>"+(list?"\n📅 نزدیک‌ترین سررسیدها:"+list:"");}
 return "ناشناخته";
}

// ---------- Charts (branded, range-aware) ----------
const NF="Noto Sans Arabic";
const BRAND="سبزینه  •  پیشگامان صنعت سبز";
function baseOpts(title,o){o=o||{};const opt={devicePixelRatio:2,layout:{padding:{left:12,right:18,top:6,bottom:10}},plugins:{legend:{display:!!o.legend,position:o.legendPos||"top",labels:{color:"#334155",font:{family:NF,size:12},usePointStyle:true,boxWidth:8}},title:{display:true,text:title,color:"#065F46",font:{family:NF,size:17,weight:"bold"},padding:{top:2,bottom:0}},subtitle:{display:true,text:BRAND,color:"#94A3B8",font:{family:NF,size:11},padding:{top:2,bottom:12}}}};if(o.scales!==false){opt.scales={y:{beginAtZero:true,grid:{color:"rgba(148,163,184,0.18)"},ticks:{color:"#64748B",font:{family:NF,size:11}}},x:{grid:{display:false},ticks:{color:"#64748B",font:{family:NF,size:11}}}};}return opt;}
function bar(data,color){return{label:"",data:data,backgroundColor:color,borderRadius:8,borderSkipped:false,maxBarThickness:46};}
function numbered(title,entries,color,unit){const labels=entries.map((_,i)=>String(i+1));let caption="📊 <b>"+title+"</b>";entries.forEach((e,i)=>{caption+="\n"+(i+1)+") "+e[0]+": <b>"+fmt(e[1])+"</b> "+unit;});return {config:{type:"bar",data:{labels:labels,datasets:[Object.assign(bar(entries.map((e)=>e[1]),color),{label:unit})]},options:baseOpts(title)},caption:caption};}
async function buildChart(supa,kind,range){const num=(v)=>Number(v)||0;range=range||"month";
 if(kind==="prod_daily"){const r=rangeOf(range);const q=await supa.from("daily_reports").select("date,production").gte("date",r.from).lte("date",r.to).order("date");const m={};(q.data||[]).forEach((x)=>{m[x.date]=(m[x.date]||0)+num(x.production);});const labels=Object.keys(m).sort();return {config:{type:"line",data:{labels:labels.map(jShort),datasets:[{label:"kg",data:labels.map((l)=>m[l]),borderColor:"#10B981",backgroundColor:"rgba(16,185,129,0.14)",fill:true,tension:0.4,borderWidth:3,pointRadius:3,pointBackgroundColor:"#10B981",pointBorderColor:"#ffffff",pointBorderWidth:2}]},options:baseOpts("روند تولید روزانه — "+r.label)},caption:"📊 <b>روند تولید روزانه — "+r.label+"</b>\nواحد: کیلوگرم"};}
 if(kind==="waste_daily"){const r=rangeOf(range);const q=await supa.from("daily_reports").select("date,waste").gte("date",r.from).lte("date",r.to).order("date");const m={};(q.data||[]).forEach((x)=>{m[x.date]=(m[x.date]||0)+num(x.waste);});const labels=Object.keys(m).sort();return {config:{type:"line",data:{labels:labels.map(jShort),datasets:[{label:"kg",data:labels.map((l)=>m[l]),borderColor:"#EF4444",backgroundColor:"rgba(239,68,68,0.14)",fill:true,tension:0.4,borderWidth:3,pointRadius:3,pointBackgroundColor:"#EF4444",pointBorderColor:"#ffffff",pointBorderWidth:2}]},options:baseOpts("روند ضایعات روزانه — "+r.label)},caption:"📊 <b>روند ضایعات روزانه — "+r.label+"</b>\nواحد: کیلوگرم"};}
 if(kind==="stops_type"){const r=rangeOf(range);const q=await supa.from("production_stops").select("stop_type,duration_min").gte("stop_date",r.from).lte("stop_date",r.to);const m={production:0,technical:0,other:0};(q.data||[]).forEach((x)=>{m[x.stop_type]=(m[x.stop_type]||0)+num(x.duration_min);});return {config:{type:"doughnut",data:{labels:["توقف تولید","توقف فنی","سایر"],datasets:[{data:[m.production,m.technical,m.other],backgroundColor:["#3B82F6","#EF4444","#F59E0B"],borderColor:"#ffffff",borderWidth:2}]},options:baseOpts("توقفات به تفکیک نوع — "+r.label,{legend:true,legendPos:"right",scales:false})},caption:"📊 <b>توقفات به تفکیک نوع — "+r.label+"</b>\nواحد: دقیقه"};}
 if(kind==="prod_line"){const q=await supa.from("daily_reports").select("date,production,line");const months={};const set={};(q.data||[]).forEach((x)=>{const mm=jMonth(x.date);if(!mm)return;const L=!x.line?"?":(/۲|2/.test(x.line)?"خط ۲":(/۱|1/.test(x.line)?"خط ۱":String(x.line)));set[L]=1;if(!months[mm])months[mm]={};months[mm][L]=(months[mm][L]||0)+num(x.production);});const labels=Object.keys(months).sort().slice(-6);const lines=Object.keys(set);const colors={"خط ۱":"#10B981","خط ۲":"#3B82F6"};return {config:{type:"bar",data:{labels:labels,datasets:lines.map((L)=>Object.assign(bar(labels.map((mm)=>months[mm][L]||0),colors[L]||"#9CA3AF"),{label:L}))},options:baseOpts("تولید ماهانه به تفکیک خط",{legend:true})},caption:"📊 <b>تولید ماهانه به تفکیک خط</b>\nواحد: کیلوگرم"};}
 if(kind==="sales_monthly"){const q=await supa.from("invoices").select("invoice_date,total");const m={};(q.data||[]).forEach((x)=>{const mm=jMonth(x.invoice_date);if(mm)m[mm]=(m[mm]||0)+num(x.total);});const labels=Object.keys(m).sort().slice(-6);return {config:{type:"bar",data:{labels:labels,datasets:[Object.assign(bar(labels.map((l)=>m[l]),"#6366F1"),{label:"ریال"})]},options:baseOpts("فروش ماهانه")},caption:"📊 <b>فروش ماهانه</b>\nواحد: ریال"};}
 if(kind==="aging"){const q=await supa.from("invoices").select("invoice_date,total,paid");const today=Date.now();const b={b0:0,b30:0,b60:0,b90:0};(q.data||[]).forEach((x)=>{const bal=num(x.total)-num(x.paid);if(bal<=0)return;const d=x.invoice_date?Math.floor((today-new Date(x.invoice_date+"T00:00:00").getTime())/864e5):0;if(d<=30)b.b0+=bal;else if(d<=60)b.b30+=bal;else if(d<=90)b.b60+=bal;else b.b90+=bal;});return {config:{type:"doughnut",data:{labels:["۰ تا ۳۰ روز","۳۱ تا ۶۰","۶۱ تا ۹۰","بیش از ۹۰"],datasets:[{data:[b.b0,b.b30,b.b60,b.b90],backgroundColor:["#10B981","#F59E0B","#F97316","#EF4444"],borderColor:"#ffffff",borderWidth:2}]},options:baseOpts("سن بدهی مشتریان",{legend:true,legendPos:"right",scales:false})},caption:"📊 <b>سن بدهی مشتریان</b>\nواحد: ریال (بر حسب روز)"};}
 if(kind==="cash"){const qa=await supa.from("treasury_accounts").select("id,name,opening_balance");const qt=await supa.from("treasury_transactions").select("treasury_account_id,direction,amount");const bal={};(qa.data||[]).forEach((a)=>{bal[a.id]={name:a.name,v:num(a.opening_balance)};});(qt.data||[]).forEach((t)=>{if(bal[t.treasury_account_id])bal[t.treasury_account_id].v+=(t.direction==="receipt"?1:-1)*num(t.amount);});const entries=Object.values(bal).map((x)=>[x.name,x.v]);return numbered("موجودی صندوق/بانک (ریال)",entries,"#3B82F6","ریال");}
 if(kind==="raw_value"){const q=await supa.from("rawmats").select("name,stock,price");const entries=(q.data||[]).map((r)=>[r.name,num(r.stock)*num(r.price)]).sort((a,b)=>b[1]-a[1]).slice(0,8);return numbered("ارزش موجودی مواد اولیه (ریال)",entries,"#10B981","ریال");}
 if(kind==="hr_dept"){const q=await supa.from("hr_employees").select("department,active");const m={};(q.data||[]).forEach((e)=>{if(e.active===false)return;const d=e.department||"بدون واحد";m[d]=(m[d]||0)+1;});return numbered("پرسنل به تفکیک واحد (نفر)",Object.entries(m),"#A855F7","نفر");}
 return null;
}
async function sendChart(supa,chatId,kind,range){range=range||"month";const built=await buildChart(supa,kind,range);if(!built){await send(chatId,"نمودار پیدا نشد");return;}const url="https://quickchart.io/chart?w=720&h=430&version=4&bkg=%23ffffff&c="+encodeURIComponent(JSON.stringify(built.config));const body={chat_id:chatId,photo:url,caption:built.caption,parse_mode:"HTML"};const RANGEABLE={prod_daily:1,waste_daily:1,stops_type:1};if(RANGEABLE[kind]){body.reply_markup={inline_keyboard:[[{text:(range==="today"?"✅ ":"")+"دیروز",callback_data:"cht:"+kind+":today"},{text:(range==="week"?"✅ ":"")+"هفته",callback_data:"cht:"+kind+":week"},{text:(range==="month"?"✅ ":"")+"ماه",callback_data:"cht:"+kind+":month"}]]};}await tg("sendPhoto",body);}

async function callAI(cfg,messages){if(!cfg.ai_base_url||!cfg.ai_api_key)throw new Error("__NO_AI__");const res=await fetch(String(cfg.ai_base_url).replace(/\/$/,"")+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+cfg.ai_api_key},body:JSON.stringify({model:cfg.ai_model||"llama-3.3-70b-versatile",messages:messages,tools:TOOLS,tool_choice:"auto",temperature:0.3})});if(!res.ok)throw new Error("AI "+res.status+": "+(await res.text()).slice(0,180));return res.json();}
function smallTalk(t){const s=t.replace(/[؟?!.،]/g," ").trim();if(/^(سلام|درود|های|هلو|hi|hello|صبح بخیر|وقت بخیر|خسته نباشی|چطوری|خوبی)/i.test(s))return "سلام به روی ماهت 🌿 چه گزارشی می‌خوای؟ از دکمه‌های پایین کمک بگیر یا سوالت را بپرس 😊";if(/^(مرسی|ممنون|سپاس|تشکر|دمت گرم|thanks|thank you)/i.test(s))return "خواهش می‌کنم 🌿 هر وقت گزارش خواستی در خدمتم.";if(/^(خداحافظ|بای|فعلا|bye)/i.test(s))return "مراقب خودت باش 🌿";return null;}
async function activeUser(supa,chatId){const q=await supa.from("bot_users").select("*").eq("telegram_chat_id",String(chatId)).eq("active",true).maybeSingle();return q.data;}

Deno.serve(async (req)=>{
 const supa=createClient(env("SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false}});
 const cc=await supa.from("bot_config").select("*").eq("id","main").single();const cfg=cc.data;
 if(!cfg)return new Response("no config",{status:500});
 BOT_TOKEN=cfg.telegram_token;
 if(req.headers.get("X-Telegram-Bot-Api-Secret-Token")!==cfg.webhook_secret)return new Response("unauthorized",{status:401});
 let update;try{update=await req.json();}catch(e){return ok();}

 if(update.callback_query){const cq=update.callback_query;const chatId=cq.message&&cq.message.chat&&cq.message.chat.id;const data=String(cq.data||"");await tg("answerCallbackQuery",{callback_query_id:cq.id});const bu=await activeUser(supa,chatId);if(!bu){await send(chatId,"لطفاً اول وارد شو: /start");return ok();}const parts=data.split(":");try{if(parts[0]==="rng"){await tg("sendChatAction",{chat_id:chatId,action:"typing"});await send(chatId,await reportText(supa,parts[1],parts[2]),{html:true,markup:inlineFor(parts[1],parts[2])});}else if(parts[0]==="cht"){await tg("sendChatAction",{chat_id:chatId,action:"upload_photo"});await sendChart(supa,chatId,parts[1],parts[2]||"month");}}catch(e){await send(chatId,"⚠️ خطا: "+(e&&e.message?e.message:String(e)));}return ok();}

 const msg=update.message||update.edited_message;
 if(!msg||!msg.text)return ok();
 const chatId=msg.chat.id;const text=String(msg.text).trim();
 const bu=await activeUser(supa,chatId);

 if(text==="/logout"||text==="🚪 خروج"){if(bu)await supa.from("bot_users").update({active:false}).eq("telegram_chat_id",String(chatId));await supa.from("bot_sessions").delete().eq("chat_id",String(chatId));await send(chatId,"🚪 از حسابت خارج شدی. هر وقت خواستی /start را بزن. 🌿",{markup:RM});return ok();}

 if(!bu){const sq=await supa.from("bot_sessions").select("*").eq("chat_id",String(chatId)).maybeSingle();const ses=sq.data;const fresh=ses&&(Date.now()-new Date(ses.updated_at).getTime()<15*60*1000);
  if(fresh&&ses.step==="await_user"){const username=text.replace(/^@/,"").trim().toLowerCase();if(!username||username.charAt(0)==="/"){await send(chatId,"لطفاً فقط نام کاربری‌ت را بفرست:");return ok();}await supa.from("bot_sessions").upsert({chat_id:String(chatId),step:"await_pass",temp_username:username,updated_at:new Date().toISOString()});await send(chatId,"👌 ممنون! حالا 🔑 رمز عبورت را بفرست.\n(پیام رمز بلافاصله پاک می‌شود)");return ok();}
  if(fresh&&ses.step==="await_pass"){try{await tg("deleteMessage",{chat_id:chatId,message_id:msg.message_id});}catch(e){}const username=ses.temp_username;const password=text;const anon=createClient(env("SUPABASE_URL"),env("SUPABASE_ANON_KEY"));const ar=await anon.auth.signInWithPassword({email:username.indexOf("@")>=0?username:username+FAKE_DOMAIN,password:password});if(ar.error||!ar.data||!ar.data.user){await supa.from("bot_sessions").upsert({chat_id:String(chatId),step:"await_user",temp_username:null,updated_at:new Date().toISOString()});await send(chatId,"⛔ نام کاربری یا رمز درست نبود. دوباره — 👤 نام کاربری‌ت را بفرست:");return ok();}const pq=await supa.from("profiles").select("id,name,role_label,active").eq("id",ar.data.user.id).single();const prof=pq.data;if(!prof||prof.active===false){await supa.from("bot_sessions").delete().eq("chat_id",String(chatId));await send(chatId,"⛔ حسابت غیرفعال است.");return ok();}await supa.from("bot_users").upsert({telegram_chat_id:String(chatId),profile_id:prof.id,display_name:prof.name||username,role_label:prof.role_label||null,active:true},{onConflict:"telegram_chat_id"});await supa.from("bot_sessions").delete().eq("chat_id",String(chatId));await send(chatId,"🌿 خوش اومدی <b>"+esc(prof.name||username)+"</b> جان!\nمن سبزینه‌ام، در خدمتتم. 👇",{html:true,markup:KB});return ok();}
  await supa.from("bot_sessions").upsert({chat_id:String(chatId),step:"await_user",temp_username:null,updated_at:new Date().toISOString()});await send(chatId,"سلام 🌿 من «سبزینه»، دستیار هوشمند گزارش‌گیری پیشگامان صنعت سبز هستم.\n\nبرای شروع وارد شو:\n👤 نام کاربری سامانه ERP خودت را بفرست:",{markup:RM});return ok();}

 if(text==="/start"||text==="/help"||text==="❓ راهنما"){await send(chatId,"🌿 سلام <b>"+esc(bu.display_name||"")+"</b> جان!\n\n"+HELP,{html:true,markup:KB});return ok();}
 if(text==="📊 نمودارها"){await send(chatId,"📊 کدام نمودار را می‌خوای؟",{markup:CHARTS_MENU});return ok();}

 await tg("sendChatAction",{chat_id:chatId,action:"typing"});
 const kind=BTN[text]||CMD[text.split(/\s+/)[0].toLowerCase()];
 if(kind){try{await send(chatId,await reportText(supa,kind,"month"),{html:true,markup:inlineFor(kind,"month")});}catch(e){await send(chatId,"⚠️ خطا: "+(e&&e.message?e.message:String(e)));}return ok();}
 const stt=smallTalk(text);if(stt){await send(chatId,stt,{markup:KB});return ok();}

 const n=new Date();const sys="تو «سبزینه» هستی — دستیار هوش مصنوعی مهربان و حرفه‌ای پیشگامان صنعت سبز (کاغذ سنگی). لحن گرم و کوتاه. برای گزارش حتماً از ابزارها استفاده کن. اعداد با جداکننده هزارگان. اگر داده نبود صادقانه بگو. امروز "+isoOf(n)+" (شمسی "+toJalali(n.getFullYear(),n.getMonth()+1,n.getDate())+"). تاریخ شمسی/نسبی را خودت تبدیل کن یا همان کلمه را به ابزار بده.";
 const messages=[{role:"system",content:sys},{role:"user",content:text}];const used=[];let answer="";
 try{for(let step=0;step<5;step++){const j=await callAI(cfg,messages);const m=j.choices&&j.choices[0]&&j.choices[0].message;if(!m){answer="پاسخی دریافت نشد.";break;}messages.push(m);if(m.tool_calls&&m.tool_calls.length){for(const tc of m.tool_calls){let a={};try{a=JSON.parse(tc.function.arguments||"{}");}catch(e){}used.push({name:tc.function.name,args:a});const rr=await runTool(supa,tc.function.name,a);messages.push({role:"tool",tool_call_id:tc.id,content:JSON.stringify(rr)});}continue;}answer=m.content||"";break;}}catch(e){if(e&&e.message==="__NO_AI__"){await send(chatId,"🤖 فعلاً بخش سوال آزاد فعال نیست؛ از دکمه‌ها استفاده کن.",{markup:KB});return ok();}answer="⚠️ ببخشید، مشکلی پیش اومد: "+(e&&e.message?e.message:String(e));}
 if(!answer)answer="ببخشید، متوجه نشدم. می‌تونی واضح‌تر بپرسی یا از دکمه‌ها استفاده کنی؟";
 await send(chatId,answer,{markup:KB});
 try{await supa.from("bot_log").insert({telegram_chat_id:String(chatId),question:text,answer:answer,tool_calls:used});}catch(e){}
 return ok();
});
